Repository epics-extensions/EPNix, pull requests merged in 2024-07, with the labels that each got.

#110 pyepics: init at 3.5.6
  ioc/tests/default.nix
  ioc/tests/pyepics/default.nix
  pkgs/default.nix
  pkgs/epnix/python-modules/pyepics/default.nix
Labels: backport nixos-23.05

#109 epics-base7: 7.0.8 -> 7.0.8.1
  pkgs/default.nix
  pkgs/epnix/epics-base/default.nix
Labels: backport nixos-23.11

#117 olog 4.7.7 + remove sed to build a valid jar
  pkgs/epnix/tools/phoebus/olog/default.nix
Labels: backport nixos-23.11

#112 linuxPackages.mrf: init at 2.6.0
  flake.nix
  pkgs/default.nix
  pkgs/epnix/kernel-modules/mrf/default.nix
  pkgs/tests/default.nix
Labels: backport nixos-23.11, backport nixos-23.05
